name: Deploy Website to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Copy files to EC2
    runs-on: ubuntu-latest

    steps:
      # Step 1: GitHub se aapka sara code uthana
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: SCP tool use kar ke index.html ko EC2 par bhejna
      - name: Copy index.html via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "index.html"
          target: "/var/www/html/"
          # Yeh nichy wali line zaroori hai taake index.html folder ke bajaye direct file ban kar jaye
          strip_components: 0
